on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
    build:
        runs-on: high-performance
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: install docker emulation
          run: docker run --rm --privileged tonistiigi/binfmt:latest --install amd64,arm64

        - name: Set up buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to ghcr.io
          run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        - name: Build and push
          run: |
            docker buildx build --platform linux/amd64,linux/arm64 -t $(echo 'ghcr.io/${{ github.repository }}/action-phpcs-code-review:${{ github.ref_name }}' | tr '[:upper:]' '[:lower:]') --push .