on: pull_request

name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run PHPCS inspection
      uses: iamimmanuelraj/action-phpcs-code-review@master
      env:
        GH_BOT_TOKEN: ${{ secrets.GH_TOKEN }}
